server:
  port: 8088
spring:
  application:
    name: pmis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wayen
    username: wayen
    password: wayen123
mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:configs/mybatis-configs.xml
